apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-app-service
  labels:
    app: cicd-demo-app
spec:
  type: NodePort
  selector:
    app: cicd-demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30090
    name: http
